SIREDOC/Controllers/AuthController.cs
using System.Security.Claims;
using SIREDOC.DB;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

namespace SIREDOC.Controllers;


public class AuthController : Controller
{
    private DbEntities _dbEntities;
    public AuthController(DbEntities dbEntities)
    {
        _dbEntities = dbEntities;
    }
    [HttpGet]
    public IActionResult Login()
    {
        return View();
    }
    [HttpPost]
    public IActionResult Login(string username, string password)
    {
        //si el usuario existe en la base de datos generar la cookie, caso contrario mostrar mensaje de usuario y password erroneo
        if (_dbEntities.Usuarios.Any(x => x.Username == username && x.Password == password))
        {
            var claims = new List<Claim>()
            {
                new Claim(ClaimTypes.Name, username),
            };
            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);
            
            HttpContext.SignInAsync(claimsPrincipal);
            
            return RedirectToAction("Index", "Documento");
        }
        ModelState.AddModelError("AuthError", "Usuario y/o contraseña erronea");
        return View();
    }

    [HttpGet]
    public IActionResult Logout()
    {
        HttpContext.SignOutAsync();
        return RedirectToAction("Login");

    }
}

SIREDOC/Controllers/EfectivoPolicialController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SIREDOC.DB;
using SIREDOC.Models;
using SIREDOC.Repositories;

namespace SIREDOC.Controllers;

[Authorize]
public class EfectivoPolicialController : Controller
{
    private readonly IEfectivoPolicialRepositorio _efectivoPolicialRepositorio;
    private readonly IUnidadPolicialRepositorio _unidadPolicialRepositorio;
    private DbEntities _dbEntities;

    public EfectivoPolicialController(IEfectivoPolicialRepositorio efectivoPolicialRepositorio, IUnidadPolicialRepositorio unidadPolicialRepositorio, DbEntities dbEntities)
    {
        _efectivoPolicialRepositorio = efectivoPolicialRepositorio;
        _unidadPolicialRepositorio = unidadPolicialRepositorio;
        _dbEntities = dbEntities;
    }
    [HttpGet]
    public IActionResult Index()
    {

        var unidades = _efectivoPolicialRepositorio.ObtenerEfectivosTodos();
        
        return View(unidades);
    }
    
    [HttpGet]
    public IActionResult Create()
    {
        ViewBag.Unidad = _unidadPolicialRepositorio.ObtenerTodos();
        return View(new EfectivoPolicial());
    }
    
    [HttpPost]
    public IActionResult Create(EfectivoPolicial efectivos)
    {

        if (efectivos.UnidadId > 6 || efectivos.UnidadId < 1)
        {
            ModelState.AddModelError("UnidadId", "La unidad policial no existe");
        }

        if (!ModelState.IsValid)
        {
            ViewBag.Unidad = _unidadPolicialRepositorio.ObtenerTodos();
            return View("Create", efectivos);
        }

        _efectivoPolicialRepositorio.GuardarEfectivo(efectivos);
        TempData["SuccessMessage"] = "Efectivo guardado correctamente";
        return RedirectToAction("Index");
    }
    
    [HttpGet]
    public IActionResult Edit(int id)
    {
       var efectivo = _efectivoPolicialRepositorio.ObtenerEfectivoPorId(id);
        ViewBag.Unidad = _unidadPolicialRepositorio.ObtenerTodos();
        return View(efectivo);
    }
    
    [HttpPost]
    public IActionResult Edit(int id, EfectivoPolicial efectivos)
    {
        if (!ModelState.IsValid) {
            ViewBag.Persona = _dbEntities.UnidadPolicials.ToList();
            return View("Edit", efectivos);
        }
        
        _efectivoPolicialRepositorio.EditarEfectivoPorId(id, efectivos);
        TempData["SuccessMessage"] = "Efectivo editado correctamente";
        return RedirectToAction("Index");
    }
    
    [HttpGet]
    public IActionResult Delete(int id)
    {
        _efectivoPolicialRepositorio.DeleteEfectivo(id);
        TempData["SuccessMessage"] = "Efectivo eliminado correctamente";
        return RedirectToAction("Index");
    }
    
}

SIREDOC/Controllers/UnidadPolicialController.cs
using Microsoft.AspNetCore.Mvc;
using SIREDOC.DB;
using SIREDOC.Models;
using SIREDOC.Repositories;

namespace SIREDOC.Controllers;

public class UnidadPolicialController : Controller
{
    private readonly IUnidadPolicialRepositorio _unidadPolicialRepositorio;
    private DbEntities _dbEntities;

    public UnidadPolicialController(IUnidadPolicialRepositorio unidadPolicialRepositorio, DbEntities dbEntities)
    {
        _unidadPolicialRepositorio = unidadPolicialRepositorio;
        _dbEntities = dbEntities;
    }
    [HttpGet]
    public IActionResult Index()
    {
        
        var items = _unidadPolicialRepositorio.ObtenerTodos();
        
        return View(items);
    }
    
    [HttpGet]
    public IActionResult Create()
    {
        ViewBag.Unidad = _unidadPolicialRepositorio.ObtenerTodos();
        return View(new UnidadPolicial());
    }
    
    [HttpPost]
    public IActionResult Create(UnidadPolicial unidades)
    {
        
        var unidad = _unidadPolicialRepositorio.ContarPorNombre(unidades);

        if (unidad > 0)
        {
            ModelState.AddModelError("Nombre", "Nombre de la unidad ya existe");
        }
        

        if (!ModelState.IsValid)
        {
           ViewBag.TipoDeCuentas = _unidadPolicialRepositorio.ObtenerTodos();
            return View("Create", unidades);
        }

        _unidadPolicialRepositorio.GuardarUnidad(unidades);
        TempData["SuccessMessage"] = "Unidad agregada correctamente";
        return RedirectToAction("Index");
    }
    
    [HttpGet]
    public IActionResult Edit(int id)
    {
        var unidad = _unidadPolicialRepositorio.ObtenerUnidadPorId(id);
        ViewBag.Unidad = _unidadPolicialRepositorio.ObtenerTodos();
        
        return View(unidad);
    }
    
    [HttpPost]
    public IActionResult Edit(int id, UnidadPolicial unidad)
    {
        if (!ModelState.IsValid) {
            ViewBag.Unidad = _dbEntities.UnidadPolicials.ToList();
            return View("Edit", unidad);
        }
       
        _unidadPolicialRepositorio.EditarUnidadPorId(id, unidad);
        TempData["SuccessMessage"] = "Unidad editada correctamente";
        return RedirectToAction("Index");
    }
    
    [HttpGet]
    public IActionResult Delete(int id)
    {
       
        _unidadPolicialRepositorio.DeleteUnidad(id);
        TempData["SuccessMessage"] = "Unidad eliminada correctamente";
        return RedirectToAction("Index");
    }
}

SIREDOC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title >@ViewData["Title"] - SIREDOC</title>
   
    <!-- Boostrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    
    <!-- Site -->
    <link rel="stylesheet" href="~/css/Site.css">
    <script src="~/js/Site.js"></script>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/SIREDOC.styles.css" asp-append-version="true"/>
</head>
<body>

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-4">
      
          <div class="container-fluid" style="background: greenyellow">
                      <img src="/img/logopnp.png" alt="" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" img>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                              aria-expanded="false" aria-label="Toggle navigation">
                          <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="navbar-collapse collapse d-sm-inline-flex">
                          
                          <ul class="navbar-nav flex-grow-1">
                              <li class="nav-item">
                                  <a class="nav-link text-dark form-control-lg" asp-area="" asp-controller="Home" asp-action="Index"><strong>Inicio</strong></a>
                              </li>
                             
                              <li class="nav-item">
                                  <a class="nav-link text-dark form-control-lg" asp-area="" asp-controller="Documento" asp-action="Index"><strong>Documentos</strong></a>
                              </li>
                              <li class="nav-item">
                                  <a class="nav-link text-dark form-control-lg" asp-area="" asp-controller="EfectivoPolicial" asp-action="Index"><strong>Efectivos</strong></a>
                              </li>
          
                              <li class="nav-item">
                                  <a class="nav-link text-dark form-control-lg" asp-area="" asp-controller="UnidadPolicial" asp-action="Index"><strong>Unidades</strong></a>
                              </li>
                              
                              <li class="nav-item">
                                  <a class="nav-link text-dark form-control-lg" asp-area="" asp-controller="Home" asp-action="Contacto"><strong>Contáctanos</strong></a>
                              </li>

                          </ul>

                      </div>
                      
                      <div>
                          
                          <ul class="navbar-nav">
                              
                              <li class="nav-item">
                                  <a class=" nav-link navbar-light text-dark form-control-sm" style="color: yellow" asp-area="" asp-controller="Auth" asp-action="Login"><strong><em class="bi bi-person-fill"></em>Login</strong></a>
                              </li>

                              <li class="nav-item">
                                  <a class=" nav-link navbar-light text-dark form-control-sm" style="color: yellow" asp-area="" asp-controller="Auth" asp-action="Logout"><strong><em class="bi bi-door-closed-fill"></em>Logout</strong></a>
                              </li>
                          </ul>
                      </div>
                      
          </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="text-center text-white" style="background-color: #0a4275;">
    <div class="container p-4 pb-0">
        &copy; 2022 - SIREDOC - <a asp-area="" asp-controller="Home" asp-action="Privacy" style="color: yellow">Universidad Privada del Norte</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)

</body>
</html>